# Generated by Django 6.0.5 on 2026-05-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0002_my_projects_projectimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MY_Projects',
            new_name='MY_Project',
        ),
    ]
