# Generated by Django 6.0.5 on 2026-05-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0003_rename_my_projects_my_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
