# Generated by Django 6.0.5 on 2026-05-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0004_my_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_skills',
            new_name='My_skill',
        ),
    ]
