# Generated by Django 6.0.5 on 2026-05-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0007_my_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Your_email', models.EmailField(max_length=254)),
                ('You_are', models.CharField(choices=[('s', 'Student'), ('e', 'Employer'), ('o', 'others')], max_length=1)),
                ('Message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
