# Generated by Django 6.0.5 on 2026-06-06 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecttech_stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_stack', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='portfolio_pages.my_project')),
            ],
        ),
    ]
