# Generated by Django 6.0.5 on 2026-06-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0010_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
