# Generated by Django 6.0.5 on 2026-06-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0011_alter_cv_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='CV',
        ),
        migrations.AddField(
            model_name='cv',
            name='cv',
            field=models.FileField(default=1, upload_to='cv/'),
        ),
    ]
