# Generated by Django 6.0.5 on 2026-06-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0012_rename_title_cv_title_remove_cv_cv_cv_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv',
            field=models.FileField(upload_to='cv/'),
        ),
    ]
