# Generated by Django 6.0.5 on 2026-06-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0013_alter_cv_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='content',
            field=models.TextField(),
        ),
    ]
